#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, threading
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A, RCODE




class Server:
    def __init__(self, root_ip, domain, port):
        self.root_ip = root_ip
        self.domain = domain
        self.origin = None
        
        self.zone = {}
        self.cache = {}
        
        
        self.get_zone_file(domain)

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        #self.socket.bind(("0.0.0.0", port))
        
        #
        self.socket.bind(("127.0.0.1", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message):
        self.log("Sending message:\n%s" % message)
        self.socket.sendto(message.pack(), addr)
        
    #send question query
    def send_query_DNS(self, dest_addr, qname, qtype):
        
        #build packet
        question = DNSRecord.question(qname, qtype=QTYPE[qtype], )
        
        #send it to server
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        
        # s.bind((dest_addr, 60531))
        s.settimeout(2)
        s.sendto(question.pack(), (dest_addr, 60053))
        
        #wait and parse for responsess
        
        
        data, addr = s.recvfrom(65535)
        s.close()
        return DNSRecord.parse(data)
        
        pass

    # need to check if the end matches 
    # ie. *.bailiwick.foo. != *.bailiwick.bar.
    #     ns.bailiwick.foo. == *.bailiwick.bar.
    def check_name_and_zone(self, name, zone):
        name = str(name)
        zone = str(zone)

        # forces the dot notation
        if not name.endswith("."):
            name += "."
        if not zone.endswith("."):
            zone += "."

        return name == zone or name.endswith("." + zone)

    def recursive_lookup(self, qname, qtype, serverIP, zone=None):
        # set the base at root dot .
        if serverIP is None:
            serverIP = self.root_ip
            zone = '.'

        # check cache
        if (qname, qtype) in self.cache:
            # remove expired entries:
            self.cache[(qname, qtype)] = [(rr, exp_time) for rr, exp_time in self.cache[(qname, qtype)]
                                          if time.time() < exp_time ]
            
            # update all the time to lives
            if self.cache[(qname, qtype)]:
                for rr, exp_time in self.cache[(qname, qtype)]:
                    rr.ttl = int(exp_time - time.time())
                
                # i have to rebuild the cache
                holder_record = DNSRecord()
                holder_record.header.rcode = RCODE.NOERROR

                for rr, exp_time in self.cache[(qname, qtype)]:
                    holder_record.rr.append(rr)
                
                # i have to seperate NS records from glue records - b/c NS is a chain it
                # will have its own records that also need to be in the cache
                for rr in holder_record.rr:
                    if rr.rtype == QTYPE.NS:
                        nsName = str(rr.rdata).lower()

                        # 
                        if (nsName, QTYPE.A) in self.cache:
                            self.cache[(nsName, QTYPE.A)] = [(r_entry, e_time) for r_entry, e_time in self.cache[nsName, QTYPE.A] 
                                                             if time.time() < e_time]
                            if self.cache[(nsName, QTYPE.A)]:
                                for glue_rr, glue_expTime in self.cache[(nsName, QTYPE.A)]:
                                    glue_rr.ttl = int(glue_expTime - time.time())
                                    holder_record.ar.append(glue_rr)
                            else:
                                del self.cache[(nsName, QTYPE.A)]

                return holder_record
            else:
                del self.cache[(qname, qtype)]


        res = self.send_query_DNS(serverIP, qname, qtype)
        
        # if there are no records then just return nothing
        if res is None:
            return None

        # bailiwick checking >> we need to check if the name fits in the zone

        # if the base isn't the root then have to check all the answers:
        if zone != '.':
            # if the name isn't in the zone then we will throw out the answer
            res.rr   = [rr for rr in res.rr if self.check_name_and_zone(rr.rname, zone)]
            res.auth = [rr for rr in res.auth if self.check_name_and_zone(rr.rname, zone)]
            res.ar   = [rr for rr in res.ar if self.check_name_and_zone(rr.rname, zone)]
        

        # need to be a little more picky when we still have records left:
        if res.rr:
            aliases_rrs = []
            if qtype == QTYPE.A:
                aliases_rrs = [rr for rr in res.rr if (rr.rtype == QTYPE.CNAME and rr.rtype != QTYPE.A)]
            
            # if there an alias, recurse and loopup server
            if aliases_rrs: #and not a_rrs:
                # We got a alias but no A record — go through the chain
                alias_name = str(aliases_rrs[-1].rdata)
                if not alias_name.endswith('.'):
                    alias_name += '.'
                
                # Resolve the CNAME target from scratch (root)
                last_known_alias = self.recursive_lookup(alias_name, QTYPE.A, None)
                
                if last_known_alias and last_known_alias.rr:
                    # Append the tail results onto our current answer
                    res.rr = res.rr + last_known_alias.rr

            # add to cache:
            for rr in res.rr + res.ar:
                if rr.ttl > 0:
                    exp_time = time.time() + rr.ttl
                    
                    # if the entry doesn't exist create one
                    if(str(rr.rname).lower(), rr.rtype) not in self.cache:
                        self.cache[(str(rr.rname).lower(), rr.rtype)] = []

                    self.cache[(str(rr.rname).lower(), rr.rtype)].append((rr, exp_time))
                    
            return res
        
        # if there's not an error or its authoriative we can still return
        if res.header.rcode == RCODE.NOERROR and not res.auth:
            return res

        # If we asked for NS, return a NS record 
        if qtype == QTYPE.NS:
            for authRR in res.auth:
                if authRR.rtype == QTYPE.NS and str(authRR.rname).lower() == qname.lower():
                    res.rr = [rr for rr in res.auth
                            if rr.rtype == QTYPE.NS
                            and str(rr.rname).lower() == qname.lower()]
                    return res

        # Follow NS referrals in the authority section 
        for authAns in res.auth:
            if authAns.rtype == QTYPE.NS:
                name = str(authAns.rdata)
                
                # need to update the zone when you are following chain of ns records
                next_zone = str(authAns.rname).lower()
                if not next_zone.endswith('.'):
                    next_zone += '.'

                ip = None
                for ip_sec in res.ar:
                    if name.lower() == str(ip_sec.rname).lower():
                        ip = str(ip_sec.rdata) 
                        break
                    
                if ip is None:
                    nsRecods = self.recursive_lookup(name,QTYPE.A,None)
                    if nsRecods:
                        ip = str(nsRecods.rr[0].rdata)

                if ip:
                    # Recurse with the correct bailiwick for the next server
                    return self.recursive_lookup(qname, qtype, ip, next_zone)

        # self.log("=============== made out here:: %s" % qname)
        return None
        
    def get_zone_file(self, zfile):
        
        with open(zfile) as zf:
            text = zf.read()
        
        for r in RR.fromZone(text):
            name = str(r.rname)
            name = name.lower()
            # check if it exists in zone dict already
            if (name, r.rtype) in self.zone:
                self.zone[(name, r.rtype)].append(r)
            else:
                self.zone[(name, r.rtype)] = [r]
                
            if self.origin is None and r.rtype == QTYPE.SOA:
                self.origin = name
                self.log("============setting authoritative server ===========:\n=========:: %s ::========" % name)
                    
        return
    
    def authoritative_send(self, request, addr):
        rep = request.reply()
        rep.header.aa = 1
        
        # get the question name from the question section in the packet and get the type
        qname = str(request.q.qname).lower()
        qtype = request.q.qtype
        
        if (qname, qtype) in self.zone:
            records = self.zone[(qname, qtype)]
            for r in records:
                rep.add_answer(r)


            if qtype == QTYPE.NS:
                for ns_rr in records:
                    ns_name = str(ns_rr.rdata).lower()
                    # look up a record in our zone file
                    glue = self.zone.get((ns_name, QTYPE.A), [])
                    for glue_rr in glue:
                        rep.add_ar(glue_rr)
        elif (qname, QTYPE.CNAME) in self.zone:
            # CNAME chasing: return the CNAME record(s) and resolve the target if in our zone
            cname_records = self.zone[(qname, QTYPE.CNAME)]
            for cr in cname_records:
                rep.add_answer(cr)
                # if the client asked for A record but we get a CNAME resolve it 
                if qtype == QTYPE.A:
                    target = str(cr.rdata).lower()
                    if target[-1] != '.':
                        target += '.'
                    a_records = self.zone.get((target, QTYPE.A), [])
                    for ar in a_records:
                        rep.add_answer(ar)
        else:
            rep.header.rcode = RCODE.NXDOMAIN
                
        self.send(addr, rep)

    def is_authoritive(self, name):
        n = str(name).lower()
        if n[-1] != '.':
            n+='.'
        return n == self.origin or n.endswith('.' + self.origin)
    
    def query_recv(self, request, addr):
        qname = str(request.q.qname).lower()
        qtype = request.q.qtype
        
        if len(request.questions) != 1:
            reply = request.reply()
            reply.header.rcode = RCODE.SERVFAIL
            self.send(addr, reply)
            return
        
        
        self.log("############ is_authoritive(%s) = %s ############" % (request.q.qname, self.is_authoritive(request.q.qname)))
        if self.is_authoritive(request.q.qname):
            self.authoritative_send(request, addr)
            return
        else:
            # if no header then server fail 
            # if not request.header.rd:
            #     reply = request.reply()
            #     reply.header.rcode = RCODE.SERVFAIL
            #     self.send(addr, reply)
            #     return

            answers = self.recursive_lookup(qname=qname, qtype=qtype, serverIP=None)
            reply = request.reply()
            reply.header.ra = 1
            reply.header.aa = 0

            # if there are no answers found just give an errory
            if answers is None:
                reply.header.rcode = RCODE.SERVFAIL

            # answer (rr), authority (auth), and additional (ar)

            # if answers exist, send them all 
            elif answers.rr:
                # answer
                for rr in answers.rr:
                    reply.add_answer(rr)
                # additional - will contain glue records
                for ar in answers.ar:
                    reply.add_ar(ar)

            self.send(addr, reply)
            
        return
            
        
    def recv(self, socket):
        data, addr = socket.recvfrom(65535) # 65535

        # print('\nthreading count ============',str(threading.active_count()))
        self.log('\nthreading count ======  %d   ======' % threading.active_count())
        # Unpack the DNS request
        
        try:
            request = DNSRecord.parse(data)
            self.log("Received message:\n%s" % request)
        except:
            self.log("Received message DIDNT WORK")
            
            return
        
        #imp threading here so we can get multiple requests
        #got this from here https://www.geeksforgeeks.org/python/python-daemon-threads/
        thread = threading.Thread(
            target=self.query_recv,
            args=(request, addr)
        )
        thread.daemon = True
        thread.start()

        # qname = str(request.q.qname).lower()
        # qtype = request.q.qtype
        
        # if len(request.questions) != 1:
        #     reply = request.reply()
        #     reply.header.rcode = RCODE.SERVFAIL
        #     self.send(addr, reply)
        #     return
        
        
        # self.log("############ is_authoritive(%s) = %s ############" % (request.q.qname, self.is_authoritive(request.q.qname)))
        # if self.is_authoritive(request.q.qname):
        #     self.authoritative_send(request, addr)
        # else:
        #     # if no header then server fail 
        #     # if not request.header.rd:
        #     #     reply = request.reply()
        #     #     reply.header.rcode = RCODE.SERVFAIL
        #     #     self.send(addr, reply)
        #     #     return
        
        #     answers = self.recursive_lookup(qname=qname, qtype=qtype, serverIP=None)
        #     reply = request.reply()
        #     reply.header.ra = 1
        #     reply.header.aa = 0
            
        #     if answers:
        #         for rr in answers.rr:
        #             reply.add_answer(rr)
                
        #         # fix by adding ARs too
        #         for ar in answers.ar:
        #             reply.add_ar(ar)
        #     else:
        #         reply.header.rcode = RCODE.SERVFAIL
        #     self.send(addr, reply)
            
        
        
        # response = request.reply()
        # response.add_answer(RR("abc.com", QTYPE.A, rdata=A("1.2.3.4"), ttl=60))       
        
        # self.send(addr, response)


    # run the server
    def run(self):
        seq = 0
        while True:
            socks = select.select([self.socket], [], [], 0.1)[0]
            for conn in socks:
                self.recv(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()